// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJjT_sOocqcpp5jesX4XP5O3j8q14oxps',
    appId: '1:219751000005:web:10ca4484de8149e53f0dac',
    messagingSenderId: '219751000005',
    projectId: 'level-up-19583',
    authDomain: 'level-up-19583.firebaseapp.com',
    storageBucket: 'level-up-19583.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC00VfWR8cClr95tyqeWcMlBUXc8gkcxY4',
    appId: '1:219751000005:android:7f925a7321f143303f0dac',
    messagingSenderId: '219751000005',
    projectId: 'level-up-19583',
    storageBucket: 'level-up-19583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBHL_-TLkLtzMkmLkyxxGQfOyXMeuSEt4',
    appId: '1:219751000005:ios:d164d4ae9a94faaa3f0dac',
    messagingSenderId: '219751000005',
    projectId: 'level-up-19583',
    storageBucket: 'level-up-19583.firebasestorage.app',
    iosBundleId: 'diana.com.levelup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBHL_-TLkLtzMkmLkyxxGQfOyXMeuSEt4',
    appId: '1:219751000005:ios:d164d4ae9a94faaa3f0dac',
    messagingSenderId: '219751000005',
    projectId: 'level-up-19583',
    storageBucket: 'level-up-19583.firebasestorage.app',
    iosBundleId: 'diana.com.levelup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJjT_sOocqcpp5jesX4XP5O3j8q14oxps',
    appId: '1:219751000005:web:35fcb89de37811993f0dac',
    messagingSenderId: '219751000005',
    projectId: 'level-up-19583',
    authDomain: 'level-up-19583.firebaseapp.com',
    storageBucket: 'level-up-19583.firebasestorage.app',
  );
}
